version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/packages/sanity-color-picker'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/packages/sanity-font-picker'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/packages/sanity-range-slider'
    schedule:
      interval: 'weekly'